# Generated by Django 5.2.9 on 2025-12-04 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nom complet')),
                ('bio', models.TextField(blank=True, verbose_name='Description / Présentation')),
                ('skills', models.TextField(blank=True, verbose_name='Compétences techniques')),
                ('passions', models.TextField(blank=True, verbose_name="Passions / centres d'intérêt")),
                ('languages', models.CharField(blank=True, max_length=200, verbose_name='Langues parlées')),
                ('projects', models.TextField(blank=True, verbose_name='Projets réalisés')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Talent vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
