# Generated by Django 5.2.9 on 2025-12-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0002_alter_profile_bio_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.CharField(blank=True, max_length=200, verbose_name='Langues'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passions',
            field=models.TextField(blank=True, verbose_name='Passions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.TextField(blank=True, verbose_name='Projets réalisés'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Compétences'),
        ),
    ]
