# Generated by Django 5.2.9 on 2025-12-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0003_remove_profile_bio_remove_profile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Anonyme', max_length=150, verbose_name='Nom'),
        ),
    ]
