# Generated by Django 5.2.9 on 2025-12-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0004_remove_profile_user_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('desc', models.TextField(verbose_name='Description')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
