# Generated by Django 5.2.9 on 2025-12-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0005_collaboration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.TextField(blank=True, null=True)),
                ('passions', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('avatar_preset', models.PositiveSmallIntegerField(blank=True, help_text="Numéro d'avatar prédéfini (1-11)", null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
