# Generated by Django 5.2.9 on 2025-12-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0006_talentprofile_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TalentProfile',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_preset',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Numéro d'avatar prédéfini (1-11)", null=True),
        ),
    ]
