# Generated by Django 5.2.9 on 2025-12-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0007_delete_talentprofile_profile_avatar_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_preset',
            field=models.PositiveSmallIntegerField(default=1, help_text="Numéro d'avatar prédéfini (1-11)"),
        ),
    ]
