# Generated by Django 5.2.9 on 2025-12-05 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0008_alter_profile_avatar_preset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name="Commentaire de l'admin"),
        ),
        migrations.AddField(
            model_name='profile',
            name='proof_file',
            field=models.FileField(blank=True, help_text='Téléchargez un fichier prouvant vos talents (PDF, images, documents, archives)', null=True, upload_to='proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', 'rar'])], verbose_name='Fichier de preuve'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut de vérification'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
